### ISSUE TITLE
kubernetes - not a valid image format

### ISSUE THREAD

**Issue by DrissiReda** [sse-secure-systems/connaisseur#114]
I have deployed notary-server and signer to my kubernetes cluster, made sure all TLS is setup properly, I then deployed connaisseur, and again, all green in kubernetes.

I have signed some images in my private registry also deployed on kubernetes, but when I try to use them in kube objects I got the error: 
```
Error from server: error when creating "failed.yml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: "private-registry:30005/kibana:5.6.8" is not a valid image format.

```

The relevant logs from connaisseur pod:

```
ERROR: {'message': '"private-registry:30005/kibana:5.6.8" is not a valid image format.', 'context': {'user': 'kubernetes-admin', 'operation': 'CREATE', 'kind': 'Job', 'namespace': 'default', 'name': 'hello', 'image': 'private-registry:30005/kibana:5.6.8'}, 'detection_mode': False}
```

Is this a known bug? Is there something specific I need?

**Comment by phbelitz** [comment]
hello there! i looked into this issue and there is a problem on how we do image format validation. we are trying to split the image into it's parts, like the domain name of the registry (`private-registry:30005` in your case), the repository path within the registry (emptry in your case), the image name (`kibana`) and tag (`5.6.8`). unfortunately when doing so, we assumed that the domain name of the registry would contain a dot (.), like normal domain would usually do. this isn't the case here.

just making the dot optional, would mean that our validation would recognize `path` in the image `path/to/image:tag` as a domain name, even though it's clearly supposed to be a repository path within a registry (the default `docker.io` registry in this case).

i created a PR to change the behavior, so that if your registry does not contain a dot (e.g. `private-registry:30005`), then the port needs to be specified. thus your problem should be solved for now, once we merge the PR.

peace.

**Comment by DrissiReda** [comment]
Thank you very much, I'll rebuild the docker image with your fix and see if it works when I have the time.

**Comment by xopham** [comment]
@DrissiReda if you need to have it running before the fix is merged, you can obviously (depending on your usecase) also get it to work right now by serving your registry under a "fake" domain like `private-registry.local`. In that case, the issue wouldn't block you :wink:

**Comment by DrissiReda** [comment]
> @DrissiReda if you need to have it running before the fix is merged, you can obviously (depending on your usecase) also get it to work right now by serving your registry under a "fake" domain like `private-registry.local`. In that case, the issue wouldn't block you wink

that would work, indeed. But I don't know how much time the merge and release will take so I gotta test if it's worth the wait :)
but I'll start with custom registry first !
