### ISSUE TITLE
"automatic child approval for" behaviour

### ISSUE THREAD

**Issue by jackalsh** [sse-secure-systems/connaisseur#244]
When enforcing all images to be signed into signed, already installed pods ignore this enforcement.
When I run new pods, everything works as expected - image denied or approved based on signature.

However, if we restart already running pod we get:
`
INFO: {'message': 'automatic child approval for "docker.io/bitnami/redis-exporter:1.12.1-debian-10-r11".', 'context': {'user': 'system:serviceaccount:kube-system:statefulset-controller', 'operation': 'CREATE', 'kind': 'Pod', 'name': 'gitlab-cluster-redis-master-0', 'namespace': 'gitlab-system', 'image': 'docker.io/bitnami/redis-exporter:1.12.1-debian-10-r11'}}
`

Not sure I understand the logic. Why this image is not validated? I expect this image is denied, because it is not trusted anymore. I need to be sure all images are denied if not trusted, otherwise the whole point is missed.

What do I miss?

**Comment by phbelitz** [comment]
Ok this is a bit confusing so let me give you an example. Let's say we have the following image policy:

```yaml
policy:
- pattern: "*:*"
  validator: dockerhub_basics
  with:
    trust_root: docker_official
- pattern: "*@sha256:*"
  validator: deny
```

This policy says: validate all images that use tags and deny all images that use digests. If you now try to apply a deployment with the image `redis:alpine`, the signature of the image will be validated, the image reference changes to `redis@sha256:deadbeef...` and the deployment gets accepted. This deployment now spawns pods (actually it creates a replcationset but for simplicity let's say it spawns pods) which will have the updated image reference, so `redis@sha256:deadbeef...`. These pods will also be checked by Connaisseur, but now our image policy says: block all the pods be cause they use digests in their image reference. That's not the kind of behavior we want. You could say that this is a "misconfiguration", but we also figured that having to validate each pod again (imagine a deployment with 50 pods ...) is kind of wasteful.

So back then we saw 2 options: *First*, we ignore all resources that are created via some "parent" resource, skipping their validation. You can identify these resources, by seeing whether they have an `ownerReference` field set in their admissionRequest. This `ownerReference` points to the "parent" resource (this would be the deployment for all our pods, in the case from above). Choosing this option would mean, if someone can craft a malicious admissionRequest (which you can) and just put some `ownerReference` in there (doesn't have to be valid), Connaisseur would skip the validation. That's why we didn't go that way.

 Second option: we check the resource in the `ownerReference`, gather its image reference using the kube API and compare it to the current resources image reference If they are the same, we essentially already validated the image in the past and can skip the validation. Meaning in the case from above, Connaisseur will check the image reference of the deployment, which is `redis@sha256:deadbeef...` and compare it to the current resource (a pod) which is also `redis@sha256:deadbeef...`. Since they are the same, the pods get an automatic child approval.

 Now we realize that restarting pods will never have their signatures checked again and we definitely need to fix this, but that is how the system currently works.

 An initial idea would could be to a grace period of like 5 min, where child approval works and after that, the normal validation kicks in again. That doesn't solve the validation of like 50 pods, should they all be restarted at once, but it's a start.

 Cheers.

**Comment by xopham** [comment]
I think the problem is bigger than the specific configuration above. Specifically, since I would call the above case a misconfiguration, as you deny the images you actually want by which calling the proper image by digest would be denied whereas it would work when pulling by tag. However, in case you had a pattern that specifies the tag:
```yaml
- pattern: "docker.io/myrepo/myimage:v*"
  validator: myvalidator
```
Even in that case, after evaluation the image reference is modified and if we re-evaluate that same validator `myvalidator` would not be called again and there would be no real instruction how to validate. In case of cosign, one can simply take the digest, as it essentially works by digest and only has a loose link to the tag. However, for notary I am not sure if we could translate it back from digest to tag. But that may be one way to go: take the most specific validator for the present image reference and check whether you can identify the digest to be valid :shrug: 
Maybe, we find a smart way to avoid double validation. But we should definitely find a suitable way to solve this problem because currently we do not deny/block images that become invalid over time (e.g. signature revoked or new signed digest in case of notary).

Thanks for raising this @jackalsh. Great catch :fishing_pole_and_fish:

**Comment by jackalsh** [comment]
Probably I am missing something, but I got confused when saw you validate not only pods, but deployments and StatefulSets as well. Deployments and StatefulSets themselves are not running any code so we can focus only on the only component which does this - the pod. Probably by eliminating all this parent logic's we can simplify the architecture of the controller.

**Comment by xopham** [comment]
@jackalsh interesting thought. Do you mean in the `MutatingWebhookConfiguration` of the [webhook config](https://github.com/sse-secure-systems/connaisseur/blob/master/helm/templates/webhook/webhook.yaml#L21)? In general, that is required as e.g. deployments or StatefulSets may contain pods and if we restrict the webhook to pods only, pods within deployments will not be forwarded by the webhook to the service. I made a quick check and if I am not mistaken 'subresource' (e.g. pods in deployments) requests are not passed through the API anymore. Maybe we could try to workout something with the different resource types inside the service, but I am not really sure. Am I missing something or how do you mean it?
Really hope we find a good solution here...

On a side note: in case we manage to find a way w/o automatic child approval, we might want to expose it as an option, as I can see that for many people it might break the cluster at an unexpected time when a k8s pod in the `kube system` namespace restarts.

**Comment by xopham** [comment]
> I made a quick check and if I am not mistaken 'subresource' (e.g. pods in deployments) requests are not passed through the API anymore. Maybe we could try to workout something with the different resource types inside the service, but I am not really sure. Am I missing something or how do you mean it?

Sorry, I was actually mistaken. I checked again. It seems we could just drop everything but Pods in the webhook configuration and turn off the automatic child approval. It however comes at the disadvantage that a deployment is created successfully and only creating the pods fails and in case of a ReplicaSet the same image within each replica is again evaluated.

**Comment by jackalsh** [comment]
@xopham As we already discussed, connaisseur tries to validate all objects, as mentioned in MutatingWebhookConfiguration
`resources: ["pods", "deployments", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "jobs", "cronjobs"]`

It leads to some weird exceptions while working with couple of workloads. For example, we are using Strimzi Kafka to deploy Kafka cluster and got following issue:
`
 Message:               Failure executing: POST at: https://172.20.0.1/apis/apps/v1/namespaces/kafka-cluster/statefulsets. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. admission webhook "connaisseur-svc.connaisseur.svc" denied the request: unknown error. please check the logs..
`
Tryed to debug ClusterRole attached to connaisseur, but it seems ok. This issue happens to some part of our applications, not only Kafka, but others works without any issue. Seems like only Deployments and StatefulSets are affected. In order to fix the issue, we changed the MutatingWebhookConfiguration to watch only on Pods, as discussed in this thread.
`resources: ["pods"]`

From what I see, there are no more exceptions in the logs, Deployments and Statefulsets deployed ok, but validation works only on Pods and it seems ok. 

Can you please approve, that this configuration change will not break signing functionality from code perspective?
Should we make this change permanent as discussed in the thread? My change is only a workaround, in order to make things working, I will wait for your decision and proper solution for this.

**Comment by xopham** [comment]
@jackalsh I am really surprised about the error you posted, since Connaisseur will only check for image references. Would not see why it would fail for a service account. What does it say in the Connaisseur logs?

I have started testing restriction to pods only and for now would not see any problematic behavior.
As mentioned before, the only usability aspect that I see is that applying a deployment will succeed even though the creation of all pods may fail. That is no problem in your case, as you seem to use Helm which will drop the deployment after 5min, but in case you use raw `kubectl apply`you may not notice.

I am planning to persist this as a feature to make `automaticChildApproval` behavior selectable in #284 , like:
- `OFF` and only validated `pods`
- `ON` for ever (means once approved valid will remain approved)
- `ON`for time t (means only approved within selectable timeframe during deployment)

Will in general try to clean the overall behavior up and improve handling.

**Comment by xopham** [comment]
@jackalsh actually combining my previous comments, I could imagine that your Service Account error is a real bug and it would be good to check that via the logs if you could share those
