### ISSUE TITLE
Reinstallation of connaisseur not possible after uninstalling connaisseur.

### ISSUE THREAD

**Issue by QWERTY92009** [sse-secure-systems/connaisseur#275]
**Describe the bug**
Connaisseur was installed using the generic instructions using a helm chart: 
- helm install connaisseur helm --atomic --create-namespace --namespace connaisseur

Connaisseur was uninstalled using the generic uninstall instructions: 
- helm uninstall connaisseur --namespace connaisseur 

On attempting to reinstall, helm reports: 
- Error: cannot re-use a name that is still in use

"helm list" returns empty.
"helm list --all" returns:
```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
connaisseur     default         1               2021-08-18 18:10:10.661030476 +0000 UTC uninstalling    connaisseur-1.0.0       2.0.0
```
The --purge flag suggested in the connaisseur documents (and elsewhere) is not recognized. 

**Expected behavior**
Following the helm uninstall connaisseur command, connaisseur is uninstalled and can be reinstalled. 

**Optional: Versions (please complete the following information as relevant):**
 - OS: Linux version 4.15.0-151-generic (buildd@lgw01-amd64-042) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021
 - Kubernetes Cluster: v1.21.4
 - Notary Server: N/A
 - Container registry: N/A
 - Connaisseur: v1.0.0
 - Other: Helm v3.6.3

**Optional: Additional context**
<Add any other context or screenshots about the bug here.>

**Comment by xopham** [comment]
Hi @QWERTY92009 thanks for reaching out. If everything goes wrong, you should be able to remove everything either via:
```bash
kubectl delete all,mutatingwebhookconfigurations,clusterroles,clusterrolebindings,configmaps,imagepolicies,secrets,serviceaccounts,customresourcedefinitions -lapp.kubernetes.io/instance=connaisseur
kubectl delete customresourcedefinitions imagepolicies.connaisseur.policy
kubectl delete namespaces connaisseur
```
or alternatively via:
```bash
make annihilate
```
Hope that fixes the issue :pray: Let me know if it worked.

For tracking the root cause and avoid such things in the future:
- Would you mind letting me know which version of Connaisseur is indicated in line 4 of `helm/values.yaml`?
- Did you have a prior version of Connaisseur installed?
- Were there any errors during de-installation?

We are currently trying track down such usability issues.

**Comment by xopham** [comment]
The `--purge` flag does not exist for Helm anymore which is why it is not recognized. I tried to remove it everywhere in the docs, but just noticed that I missed it in the main README.md. Raised an issue for that #276 and will fix asap.

Btw. you can find more detailed information in the main docs: https://sse-secure-systems.github.io/connaisseur/v2.1.0/

**Comment by QWERTY92009** [comment]
Thanks so much @xopham! I'm testing right now, but in the meantime:

- Version: image: securesystemsengineering/connaisseur:v2.1.0
- No prior version of Connaisseur installed.
- I don't recall any errors on de-installation.

**Comment by xopham** [comment]
Thank you :pray:

**Comment by QWERTY92009** [comment]
@xopham It looks like your deinstallation instructions worked. Thanks!

**Comment by xopham** [comment]
@QWERTY92009 happy to hear :-)
Feel free to share any further insights. There is also [discussions](https://github.com/sse-secure-systems/connaisseur/discussions) for feedback and support
