### ISSUE TITLE
context deadline exceeded - too many times before it actually succeeds in verifying image sign

### ISSUE THREAD

**Issue by aneran01** [sse-secure-systems/connaisseur#532]
**Describe the bug**
Have deployed connaisseur using helm chart in AKS cluster. When deploying pod with signed / unsigned image, connaisseur fails too many times with below error,

> Error from server (InternalError): error when creating "hello-world-kubs-pod.yaml": Internal error occurred: failed calling webhook "connaisseur-svc.connaisseur.svc": Post "https://connaisseur-svc.connaisseur.svc:443/mutate?timeout=30s": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

OR 

`Error from server (InternalError): error when creating "hello-world-kubs-pod.yaml": Internal error occurred: failed calling webhook "connaisseur-svc.connaisseur.svc": Post "https://connaisseur-svc.connaisseur.svc:443/mutate?timeout=30s": context deadline exceeded`

**Expected behavior**
connaisseur should perform verification and give either result based on whether the docker image pulled is signed or not.

**Optional: To reproduce**
kubectl run test --image=docker.io/securesystemsengineering/demo:test -n <namespace>

![context_issue](https://user-images.githubusercontent.com/87467109/153283645-220c1c01-2408-49d2-9f48-1ddd6d8c1577.PNG)

**Optional: Additional context**
<Add any other context or screenshots about the bug here.>

**Comment by xopham** [comment]
@aneran01 it seems that either Connaisseur cannot be reached or the validation times out. Would have a few questions about that to triangulate the problem:
* does that mean that it sometimes works, but fails other times?
* the image `docker.io/securesystemsengineering/demo:test` is not provided by us and thus there should be no images available. Our testimages are mostly `docker.io/securesystemsengineering/testimage:signed` and tag `unsigned`. Was the `demo` image mentioned anywhere?
* could you share the connaisseur logs via `kubectl logs -n connaisseur connaisseur-<your pods>` to see if any of the Connaisseur Pods receive the request and if so how they fail.
* if none of the above gives any reasonable answer it may be docker's new rate limits kicking in and blocking further requests...

Hope that helps to find the root cause :slightly_smiling_face:

**Comment by aneran01** [comment]
![image](https://user-images.githubusercontent.com/87467109/153653967-5f645ab8-0ef1-4425-9e03-31ed10eb1018.png)

**Comment by aneran01** [comment]
As u can see with docker.io/securesystemsengineering/testimage:unsigned too, it fails in between.
When it gives Client.Timeout exceeded, there are no logs in connaisseur/connaisseur-svc.
it only shows below logs,
connaisseur-deployment-6cd54d98f5-6hxgl:[2022-02-11 19:06:49,275] INFO: 10.239.20.199 - - [11/Feb/2022 19:06:49] "GET /ready HTTP/1.1" 200 -     ││ connaisseur-deployment-6cd54d98f5-cvfr7:[2022-02-11 19:06:49,271] INFO: 10.239.20.199 - - [11/Feb/2022 19:06:49] "GET /health HTTP/1.1" 200 -    ││ connaisseur-deployment-6cd54d98f5-cvfr7:[2022-02-11 19:06:49,276] INFO: 10.239.20.199 - - [11/Feb/2022 19:06:49] "GET /ready HTTP/1.1" 200 -     ││ connaisseur-deployment-6cd54d98f5-nf6h9:[2022-02-11 19:06:59,252] INFO: 10.239.20.198 - - [11/Feb/2022 19:06:59] "GET /health HTTP/1.1" 200 -    ││ connaisseur-deployment-6cd54d98f5-nf6h9:[2022-02-11 19:06:59,255] INFO: 10.239.20.198 - - [11/Feb/2022 19:06:59] "GET /ready HTTP/1.1" 200 -     ││ connaisseur-deployment-6cd54d98f5-6hxgl:[2022-02-11 19:07:19,272] INFO: 10.239.20.199 - - [11/Feb/2022 19:07:19] "GET /health HTTP/1.1" 200 -

which are health check related.

**Comment by aneran01** [comment]
![image](https://user-images.githubusercontent.com/87467109/153654672-328af9f0-f590-48db-b9b8-87aaa5259270.png)

**Comment by aneran01** [comment]
> * does that mean that it sometimes works, but fails other times?
When it works, it works perfectly fine restricting / allowing images as per scenario.

**Comment by xopham** [comment]
@aneran01 I see. From your information, I would presume that Connaisseur often runs into a timeout. The reason it reports an internal error reaching the webhook service is likely due to #448 .
To confirm this: Could you scale down Connaisseur to only 1 pod via `.deployment.replicasCount: 1` in `helm/values.yaml`, apply an image that fails with the above internal error reaching Connaisseur service and check if there is a correpsonding error message 300s after the request?
If this can be confirmed, the question is why there is bad connectivity to external resources which should however be independent of Connaisseur.

**Comment by xopham** [comment]
@aneran01 has the problem been resolved?
Will close the issue at it seems to have become stale. Feel free to re-open if the problem persists :slightly_smiling_face:
