### ISSUE TITLE
Referenced image is "not a valid image reference".

### ISSUE THREAD

**Issue by QWERTY92009** [sse-secure-systems/connaisseur#548]
**Describe the bug**
When attempting to deploy a container that should meet the policy / validator requirements, connaisseur returns this error:
"Error from server: error when creating "bandslotmgr.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: registry.docker.artifactory.sativa.com/repo/app:0.152.2-20220208T143249Z.master is not a valid image reference."

The applicable pattern configured in values.yaml is:
`"registry.docker.artifactory.sativa.com/*/*:*"`

Have also tried this pattern with the same effect:
`"registry.docker.artifactory.sativa.com/repo/*:*"`

**Expected behavior**

Expected the image to be pulled and pass signature verification.

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>

**Optional: Versions (please complete the following information as relevant):**
 - OS: Ubuntu 18.04
 - Kubernetes Cluster: Kubernetes v1.21 GKE
 - Notary Server: N/A
 - Container registry: JFrog Artifactory Enterprise Plus 7.19.12
 - Connaisseur: cloned from github 2/9/2022. Image: securesystemsengineering/connaisseur:v2.2.0
 - Other: <other relevant tools and versions>

**Optional: Additional context**

Is it possible that the periods in the image name are somehow considered delimiters, requiring some other treatment? We previously tested this without a problem, but the deployment image did not have periods.

Thanks in advance!

**Comment by xopham** [comment]
@QWERTY92009 the error results from a bug that disallowed capitalization in image tags in Connaisseur versions 2.2.1 and prior. It was only fixed in Connaisseur v2.3.0 via #393 . Since you are using v2.2.0, Connaisseur fails with this error message.
I tested and it should work without problems for versions >=2.3.0.

In general, we recommend to use the latest Connaisseur versions, as we do not backport fixes. Is there any specific reason for using Connaisseur v2.2.0?

Please let me know if that resolved the issue :slightly_smiling_face:

**Comment by QWERTY92009** [comment]
Thanks @xopham. I verified that the image pulled when there were no capital letters. I thought I had the latest distro, will upgrade immediately. Thanks again!
