### ISSUE TITLE
Deployment of signed images fails with Error: /app/connaisseur-config/v3g-beamman-val/.docker/config.json: illegal base64 data at input byte 72

### ISSUE THREAD

**Issue by QWERTY92009** [sse-secure-systems/connaisseur#550]
**Describe the bug**

The auth secret_name in connaisseur values.yaml is configured to be the same secret used to pull the images, which works when connaisseur is not installed. Also, this secret was accepted by Kubernetes apiserver, implying it is properly formatted.

The format of this secret (obtained by getting the secret using kubectl and then base64 decoding the .dockerconfigjson value) is:

```
{
    "auths": {
        "registry.docker.artifactory.sativa.com": {
            "auth": "xxxxx",
            "username": "user"
        }
    }
}
```

The full error is:

```
Error from server: error when creating "bandslotmgr.yaml": admission webhook "connaisseur-svc.connaisseur.svc" denied the request: Unexpected Cosign exception for image "registry.docker.artifactory.sativa.com/repo/app:tag": Error: /app/connaisseur-config/validator/.docker/config.json: illegal base64 data at input byte 72
main.go:46: error during command execution: /app/connaisseur-config/validator/.docker/config.json: illegal base64 data at input byte 72
```

**Expected behavior**

Expected the image to be pulled and signature verified to be correct.

**Optional: To reproduce**
<Stepwise guide or instructions or minimal example to reproduce.>

**Optional: Versions (please complete the following information as relevant):**
 - OS: Ubuntu 18.04
 - Kubernetes Cluster: GKE kubernetes v1.21
 - Notary Server:  N/A
 - Container registry: JFrog artifactory Enterprise Plus 7.19.12
 - Connaisseur: securesystemsengineering/connaisseur:v2.4.1
 - Other: <other relevant tools and versions>

**Optional: Additional context**
<Add any other context or screenshots about the bug here.>

**Comment by xopham** [comment]
@QWERTY92009 the error is surprising as it reports malformed lbase64. Have you reviewed how the base64 form looks like at byte 72? unfortunately it contains a secret such that it cannot be shared here for inspection.
- has the same secret worked for you when using the dockerconfigjson directly with cosign on your local machine?
- could you exec into the connaisseur pod and check the config.json at path `/app/connaisseur-config/validator/.docker/config.json`?

Otherwise, as Connaisseur reports this is an error originating from `cosign`. If this turns out to be a legit bug in reading a valid configjson, it would have to be reported there: https://github.com/sigstore/cosign . But I am not yet fully convinced of that.

Let me know if that helps!

**Comment by QWERTY92009** [comment]
Thanks @xopham. I'm not thoroughly convinced yet. 

However:
1. I am able to add this secret to kubernetes without any complaint.
2. I'm able to extract the secret from kubernetes and base64 decode it as indicated above, to obtain the original creds.

I will definitely follow your troubleshooting tips and get back to you!

**Comment by QWERTY92009** [comment]
@xopham. When I exec in I see /app/connaisseur-config, containing
```
-rw-r--r--    1 0        0                2 Feb 21 18:44 config-secrets.yaml
-rw-r--r--    1 0        0             1116 Feb 21 18:44 config.yaml
drwxr-xr-x    3 0        0             4096 Feb 21 18:44 v3g-beamman-val
drwxr-xr-x    3 0        0             4096 Feb 21 18:44 v3g-phyman-val
```
Note the zero size of the yamls. Within v3g-beamman-val, there are no contents. (BTW, the name of the validator is correct.)

Apparently an error in installation? I didn't see any warnings, but maybe there is a log somewhere? Thanks!

**Comment by xopham** [comment]
@QWERTY92009 did you do an `ls -la` inside `v3g-beaman-val` because the path in your case would be `/app/connaisseur-config/v3g-beaman-val/.docker/config.json` and `ls` will not reveal hidden folders/files such as `.docker`. This had to be done as `cosign` only takes the dockerconfigjson from `$HOME/.docker/config.json` and the auth creds cannot be passed as input.
In your case, the following should work `cat /app/connaisseur-config/v3g-beamman-val/.docker/config.json`.
Does that work? If that does not yield any output than there would have to be something wrong with configuration or with the installation.
If the above won't help, I could try to reproduce the error. Would you be able to share a minimal example of the bug consisting of:
* pseudonymized dockerconfigjson (auth secret replaced with non-secret value of same length and form)
* a pseudonymized `values.yaml`
* pseudonymized command you use to apply your deployment

Note that resources referenced there in would have to exist.

**Comment by QWERTY92009** [comment]
@xopham, you are correct of course. Using ls -la does reveal the file:
/app/connaisseur-config/v3g-beamman-val/.docker/config.json

The contents are exactly the contents of the config.json originally used, with the same form shown above.

**Comment by xopham** [comment]
@QWERTY92009 I was just checking if anything like this had been observed for `cosign`. Turns out `cosign` has a very [unintuitive handling of a file being unavailable](https://github.com/sigstore/cosign/issues/71) while this specific case has been fixed, I'd presume it may still be present in other configurations.
So, I rechecked the information you provided and noticed the following:
* the error you are reporting points to `/app/connaisseur-config/validator/.docker/config.json`
* the `config.json` you report above is located at `/app/connaisseur-config/v3g-beamman-val/.docker/config.json`

Was this two different configurations and typically error message and location of `config.json` are in accordance? Otherwise, this might indicate a misconfiguration in `helm/values.yaml` or a bug in authentication handling.
If possible, could you share your `helm/values.yaml` or a redacted version?

**Comment by QWERTY92009** [comment]
Thanks @xopham. The discrepancy was due to a clumsy redaction error. 

Sharing values.yaml is an excellent idea! Please take a look and let me know what you think. Thanks! 
(Note: added .txt extension due to github not liking the .yaml extension which seems strange.)
[values-redacted.yaml.txt](https://github.com/sse-secure-systems/connaisseur/files/8171074/values-redacted.yaml.txt)

**Comment by xopham** [comment]
@QWERTY92009 the `helm/values.yaml` looks unsuspicious. However, going back to the form of the secret that you provided above:
```
{
    "auths": {
        "registry.docker.artifactory.sativa.com": {
            "auth": "xxxxx",
            "username": "user"
        }
    }
}
```
I am very surprised of its form. I understand that it seems to be functional for k8s, but fails for the use case here, as cosign claims "illegal base64". I can only see 2 potential reasons rooted in cosign parsing the config.json different to kubernetes:
* either the `auth:` has some broken base64 value as described [here](https://portal2portal.blogspot.com/2021/02/argh-kubernetes-and-yaml-hell.html)
* or cosign does not do well with the `username` that is not base64 encoded to begin with

I would propose to copy that config.json to your local machine, make a backup of your `~/.docker/config.json` and copy the config.json provided here to `~/.docker/config.json`, download the `cosign` binary and attempt image verification to see whether it fails with the same issue and if so, see if that changes when removing 'username'...

**Comment by QWERTY92009** [comment]
Thanks @xopham. The auth json is created by docker, and accepted by k8s, but I think you are suggesting more closely examing its structure in case there is another incompatibility. I'll look into this. This is only a PAT, so I can send you the original and reset the PAT on my side if you are amenable to that.
