### ISSUE TITLE
Helm installation fails with timeout on k8s 1.16.x

### ISSUE THREAD

**Issue by akuma5157** [sse-secure-systems/connaisseur#58]
**Describe the bug**
Helm chart installation gets timed out waiting for readiness probe on k8s 1.16.x
Readiness probe fails maybe because MutatingWebhookConfigurations is not created at all in k8s 1.16.x

#### works fine on k8s 1.18.x as expected on the same setup.

**Expected behavior**
Helm chart installation succeeds and all 3 pods of the deployment are in ready state

**Optional: To reproduce**

Minikube
```
cd connaisseur/
sudo minikube start --driver=none --kubernetes-version=v1.16.15
sudo chown -R $USER $HOME/.kube $HOME/.minikube
make install
sudo minikube delete

sudo minikube start --driver=none --kubernetes-version=v1.18.0
sudo chown -R $USER $HOME/.kube $HOME/.minikube
make install
sudo minikube delete
```

Microk8s
```
cd connaisseur/
sudo snap refresh microk8s --classic --channel=1.16/stable
sudo microk8s start
sudo microk8s enable dns
sudo microk8s config > ~/.kube/config
make install
sudo microk8s stop

sudo snap refresh microk8s --classic --channel=1.18/stable
sudo microk8s start
sudo microk8s enable dns
sudo microk8s config > ~/.kube/config
make install
sudo microk8s stop
```

**Optional: Versions (please complete the following information as relevant):**
 - OS: Ubuntu-18.04 on wsl2
 - Kubernetes Cluster: microk8s-1.16/stable OR minikube-1.14(k8s-1.16.15, vm-driver=none)
 - Notary Server: notary.docker.io
 - Container registry: registry.docker.io
 - Connaisseur: master
 - Other: 

**Optional: Additional context**
<Add any other context or screenshots about the bug here.>

**Comment by Starkteetje** [comment]
Hi @akuma5157 

I tried setting up Connaisseur on kubernetes 1.16 with minikube (docker driver, driver none does not work with my setup) and that worked.
Maybe pulling of the Connaisseur image took longer than the [Bootstrap Sentinel Timeout](https://github.com/sse-secure-systems/connaisseur/blob/master/adr/ADR-1_connaisseur-bootstrap-sentinel.md), which can be changed [here](https://github.com/sse-secure-systems/connaisseur/blob/master/helm/values.yaml#L18). Tldr of the ADR: To ensure Connaisseur Pods dont show ready, when the webhook does not exist, they need to check for it. Its existence would block deployment of Connaisseur though, so we have a special Pod to solve this chicken-egg problem that lives for 60s by default

If increasing the timeout solves your problem, we'd be interest to get that feedback and might decide to increase the default.

I'll also try the microK8s setup just to be sure, but wanted to give you quick feedback

**Comment by Starkteetje** [comment]
I've also checked the setup on MicroK8s and for me it works. If increasing the timeout does not solve the issue, could you maybe share the output of `kubectl get all -n connaisseur` or the connaisseur pods' logs to help us pinpoint the problem.

**Comment by akuma5157** [comment]
Hi @Starkteetje ,
Thanks for the quick update.
It is indeed possible that something might be wrong with my setup as i was using it on wsl.

But i can assure you increasing the timeout did not work for me. I tried as high as 300. And also the default timeout on 1.18. Several times.
The pods were created immediately, and the logs showed 200 on both health and ready endpoints until the lifetime of bootstrap pod. And then ready started giving 500.
According to what i understood from the flask code, it checks the existence of the mutatingwebhookconfigurations object. Which wasnt present - i might be wrong here.

I did check kubectl get all, everything except the admissions controller object was created.

I will only be able to publish the logs next week as i am currently away from my system.
Please don't sweat it too much as the issue might fix itself with a fresh setup. 🤷

**Comment by Starkteetje** [comment]
Yes, the Connaisseur pods check for both the existence of the webhook (to not show ready when they would not be queried in the event of a deployment) and whether they can reach the Notary server. If both are true, they will report ready. However, since the webhook would block the Connaisseur deployment itself, we cannot deploy the webhook before the pods. Hence the bootstrap pod that "covers" for a period allowing the Connaisseur pods to report ready and cause the webhook to be deployed if they're ready otherwise.

The pods reporting ready would signal that they're ready (except for potentially the webhook), in which case the webhook should have been deployed. With `kubectl get all` it unfortunately doesn't show webhooks. You'd have to run `kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io` to see them. However, from what you describe it sounds very much like the deployment of the webhook failed for whatever reason.
It is triggered by an [install job](https://github.com/sse-secure-systems/connaisseur/blob/master/helm/templates/webhook/job.yaml) that is triggered by helm as a post-install script. What I could imaging would be that somehow the initial Connaisseur deployment does not complete and hence helm does not execute the post-install script. So it would be interesting whether `kubectl get deployments.apps` shows a 3/3 ready deployment.

Let's see whether a fresh setup works or you run into the same issue. We'll be happy to hear back from you :)

**Comment by Starkteetje** [comment]
Hey @akuma5157 
since you did not come back to us, I'll assume your issue was resolved. Feel free to reopen if you have additional questions.
