### ISSUE TITLE
Eks rejected self-sign cert for connaisseur service

### ISSUE THREAD

**Issue by brackend** [sse-secure-systems/connaisseur#599]
**Describe the bug**
Kubernetes is rejecting self-sign cert for connaisseur service as certificate signed by unknown authority

Unable to execute resource action: Internal error occurred: failed calling webhook "connaisseur-svc.connaisseur.svc": Post "https://connaisseur-svc.connaisseur.svc:443/mutate?timeout=30s": x509: certificate signed by unknown authority

**Expected behavior**
Should be accepted.  Or should be able to create a kubeapi signed tls cert.

**Optional: To reproduce**
Deploy onto eks using helm charts ( in this case through Argocd )
Deploy some container for testing purposes on a ns
Sign the container image
Apply connaisseur validate label to the namespace
Restart the deployment for the container
Error is generated

**Optional: Versions (please complete the following information as relevant):**
 - OS: Linux
 - Kubernetes Cluster: eks 
 - Notary Server: Notary
 - Container registry: harbor
 - Connaisseur: Helm chart 1.3.1
 - Other:
**Will** udpate this info

**Optional: Additional context**
I had tried to create a tls secret signed by the kubeapi CA.  But this is rejected by connaisseur

**Comment by xopham** [comment]
hey @brackend :wave:
would you mind sharing the complete log, potentially using `debug` level. Connaisseur was tested on EKS and should in general work. For now, I see several potential high-level questions that require investigation:
* is it really Connaisseur TLS cert? It might be the harbor notary cert failing that can be configured as [described in the docs](https://sse-secure-systems.github.io/connaisseur/v2.5.2/validators/notaryv1/#configuration-options)
* another root cause may be deployment via argoCD where I am not sure if that was tested

Related issues are #224, #225 and #572 . @phbelitz might have further information

**Comment by brackend** [comment]
ah super thank you for the links.   Got a better understanding of it now.
It works really well.  I'm not sure why I was getting the original error I think possibly the tls secret needed to be refreshed.

So current configuration is using self-signed with CA in admission webhook.  May change this but for now works well.

BTW: it's deployed through Argocd.  

One thing that puzzled me and which I hope to figure out.  The signed image was not using the root key I had finally used after alot of chopping and changing.   It was failing for a while with the public key I had last used.  But when I checked the image directly it was using a different public root key - maybe an earlier one.   I thought there would only be one root key - need to read up a little more to improve my understanding.

Anyway thank you for the links!
