### ISSUE TITLE
Connaisseur in EKS Environment

### ISSUE THREAD

**Issue by stevieg27** [sse-secure-systems/connaisseur#69]
I could see that content trust/notary server support in Aws ECS is still yet to implement.

https://github.com/aws/containers-roadmap/issues/43

So is it possible to deploy connaisseur without the above requirements or is there any workaround for this ?

**Comment by phbelitz** [comment]
hello there.

You can run connaisseur on EKS in combination with an ECS/ECR **if** you either run your own Notary v1 instance or use a public Notary v1 instance (like the Docker Hub one: `notary.docker.io`). For running your own, head to the [notary repo](https://github.com/theupdateframework/notary), there's also a pull request for a helm chart in there. But since this seems rather wacky and probably means a lot of work on your part, I'd recommend using the Docker Hub one. Also to make things more clear, just because you are using the Docker Hub Notary instance, doesn't mean you can't use the ECR. They are completly seperate from eachother, so there shouldn't be any incompatibility issues.

The later comments on the issue you posted are related to Notary **v2**, which is inherently different from v1. For v2 the registry  (ECR) must be changed and needs to support the new format that will be introduced. But that's future talk, as Notary v2 is currently in development and can't be used. 

So for now you're stuck with v1 and can use connaisseur without issue. I hope I answered your question with this, otherwise just write back. Cheers.
