### ISSUE TITLE
Support for multiple public keys

### ISSUE THREAD

**Issue by sr258** [sse-secure-systems/connaisseur#82]
Does connaisseur have support for multiple root public keys? We need an admissions controller that checks signatures of several images on the Docker Hub (signed by the publishers) and of some images in a private registry (Harbor, signed ourselves). From what I could gather in the readme, it looks like Connaisseur only supports one public key, so we would be limited to checking the signature of a single source. Or do I misunderstand the way connaisseur or Docker Content Trust works?

**Comment by phbelitz** [comment]
You are right. Connaisseur does currently not support multiple public keys which is not a DCT problem, but derives from the decision that we pin trust to a single root key. You could push public images to the private registry after signing with your own key. While this increases control and reduces external dependencies, there is certainly a downside of additional maintenance to keep images up-to-date.
You could also use the image policy in order to exclude the specific images from verification: https://github.com/sse-secure-systems/connaisseur#image-policy

It might be possible to add support for multiple keys. However, to understand the situation better: Do you use both notary servers from Harbor and Docker HUB?

**Comment by sr258** [comment]
We're currently planning our Kubernetes setup and we don't have established the systems yet. The need to check signatures derives from the fact that we are required to follow the principles described in requirement SYS.1.6.A6 https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Grundschutz/Drafts/Community_Draft/SYS_1_6_Container_CD.pdf?__blob=publicationFile&v=11 (it's German, but it looks like you are so too). This means that the signatures of all images that we use must be checked. We'd like to use official standard images (Redis, etc.) from the Docker Hub as well as custom ones built by ourselves or out contractors (will be put in a Harbor registry that runs Notary). So in the end, we will have to talk to both Notary server, I think.

**Comment by xopham** [comment]
fixed by #90 in Connaisseur v2.0.0. See docs: https://sse-secure-systems.github.io/connaisseur/
