### ISSUE TITLE
Connaisseur prevents downscaling of a previous replicaset during an update of a deployment.

### ISSUE THREAD

**Issue by Hannessi** [sse-secure-systems/connaisseur#820]
**Describe the bug**
Connaisseur prevents downscaling of a previous replicaset during an update of a deployment.

We run into a scenario, where after a deployment update, we have two active replicasets running at the same time.

**Expected behavior**
It is expected that older replicaset is downscaled when the new replicaset is ready.

Log message 
ERROR: {'message': 'Static deny.', 'context': {'detection_mode': False, 'user': 'system:serviceaccount:kube-system:deployment-controller', 'operation': 'UPDATE', 'kind': 'ReplicaSet', 'name': 'p1o-fe-cms-55957f46d4', 'namespace': 'o5'}}

Configuration 
  validators:
    # static validator that allows each image
    - name: allow
      type: static
      approve: true
    - name: deny
      type: static
      approve: false
    - name: p1o
      type: cosign
      trust_roots:
        - name: p1o-pipeline
          key: |
            -----BEGIN PUBLIC KEY-----
            -----END PUBLIC KEY-----
      auth:
        secret_name: harbor-registry-secret
  policy:
    - pattern: "*:*"
      validator: deny
    - pattern: "docker.xxx.xx/p1o/p1o-fe:*"
      validator: p1o
      with:
        trust_root: p1o-pipeline

**Comment by phbelitz** [comment]
Which version of Connaisseur are you running?

**Comment by Hannessi** [comment]
Connaisseur v2.6.4
Openshift 4.8.25
Kubernetes 1.21

**Comment by phbelitz** [comment]
I'm somewhat unable to reproduce this ... does this happend everytime you try to downscale a deployment or only under special occasions? And I assume all you do is `kubectl apply -f deployment.yaml`, right? 

From the error log it seems like your image reference changed during the downscaling. When you first did your deployment, everything worked I guess, since your image reference matched the pattern `"docker.xxx.xx/p1o/p1o-fe:*"`. But then with the downscaling the image reference must have changed, so that nur the rule pattern `*:*` matches, and your replicaset is denied (since you have a static deny on anything but the `"docker.xxx.xx/p1o/p1o-fe:*"` pattern).

**Comment by jakekreider** [comment]
We've run into a similar issue when tags are reused. For example, a deployment & RS point to the `:latest` tag of an image, but that tag gets updated in Notary prior to a deployment update, so the old replicaset's digest no longer matches what's in Notary. The existing replicaset fails to scale down, so the new one can't roll out past the surge limit of the deployment spec. Or at least that's what we _think_ is occurring based on logs.

**Comment by phbelitz** [comment]
I see the problem now. When the replicaset is first created, using the `:latest` tag, Connaisseur will update this tag with a digest it got from the signature validation. That's how we ensure the correct (secure) image is used. Now if you do any updates to the replicaset, all following validations will be made with the image digest and no longer with the tag `:latest`. Since Connaisseur also does verifications on digests, this may cause unexpected behavior, especially when the signature data was updated.

For example: You deployed your image with tag `:latest` which got translated to digest `123`. Now you update your signature and the digest `123` is update with `456` inside you Notary. Any updates to your replicaset (which uses digest `123`) will contact the Notary to see whether digest `123` is present, which it isn't and hence Connaisseur will block the update.

I will look into creating a feature that will automatically allow any changes to resources, that do not touch the image reference. If that works, your problem shouldn't occur anymore. In the meantime, if you can't wait any longer you can also disable digest validation altogether by creating a rule similar to this:

```yaml
- pattern: "your/registry/*@sha256:*"
  validator: allow
```

But be aware that this type of rule poses security risk! Anyone deploying images referenced by digest then can bypass your signatures. That's why we added digest validaton in the first place. Hope this helps.

**Comment by jakekreider** [comment]
Thanks @phbelitz. With our environment, we know that replicasets are only being created by the deployment controller by way of deployment resources (i.e. users don't create replica directly). Could we then exclude replicaset resources from the `MutatingWebhookConfiguration`?
